# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: zziglet
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: pricesnap
# "service" is the name of this project. This will also be added to your AWS resource names.
service: team6

stages:
  default:
    params:
      tableName: "users-table-${sls:stage}"
      productsTableName: "products-table-${sls:stage}"  # 새로운 테이블 이름 파라미터 추가

provider:
  name: aws
  runtime: nodejs20.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - execute-api:Invoke
          Resource:
            - "*"
  environment:
    USERS_TABLE: ${param:tableName}
    PRODUCTS_TABLE: ${param:productsTableName}
    SESSION_KEY: "session-key"
    MONGODB_URI: "mongodb+srv://priceSnap:priceSnap0!@pricesnap.5ibjq.mongodb.net/?retryWrites=true&w=majority&appName=PriceSnap"
    MONGODB_NAME:  "PriceSnapDB"
    USERS_COLLECTION:  "users"
    PRODUCTS_COLLECTION: "products"
     
functions:
  api:
    handler: src/index.handler
    events:
      - httpApi:  # API Gateway의 httpApi 이벤트 사용
          path: /api/{proxy+}  # 모든 /api/... 요청을 처리
          method: ANY
